### ISSUE TITLE
[Bug]: box-shadow with css var has no effect on Android

### ISSUE THREAD

**Issue by zhongyr** [lynx-family/lynx#1645]
### System Info

System: Android 

### Details

```typescript
export function App() {

  return (
    <view className='container'>
      <text>Hello, ReactLynx</text>
    </view>
  )
}
```

```css
:root {
  --tw-shadow: 0 0 0 0 transparent;
}

.container {
  --tw-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.5);
  box-shadow: var(--tw-shadow);
}
```

### Reproduce Steps

expected ：

![Image](https://github.com/user-attachments/assets/3fc30e24-694e-4b1f-914a-713d99949214)

has a shadow， currently nothing shows
