### ISSUE TITLE
[Bug]: Custom Font using @font-face not working on Android

### ISSUE THREAD

**Issue by xuanyi-fu** [lynx-family/lynx#295]
A huge thank you to @ge-exe for identifying this issue!

### System Info

Dev Server: macOS
Lynx Explorer Device: Android

### Details

Custom Font imported from the `@font-face` at-rule in CSS works in iOS but not works in Android.

```CSS
// App.css
@font-face {
  font-family: 'Doto';
  font-style: normal;
  font-weight: 100 900;
  src: url("./assets/Doto-Regular.ttf");
}

.custom-font {
  font-family: "Doto";
  font-size: 50px;
  font-weight: 100;
}
```

```typescript
// App.tsx
import './App.css'

export function App() {
  return (
    <view className='container'>
      <text className='custom-font'>Whereas recognition of the inherent dignity!</text>
    </view>
  )
}
```

iOS:

![Image](https://github.com/user-attachments/assets/5f969c80-16c8-4887-b02d-e7a6cd00d7fb)

Android:

![Image](https://github.com/user-attachments/assets/0c947bcb-3ef2-4179-86fc-95904b581e04)

### Reproduce Steps

Project to reproduce:
[custom-font-2.zip](https://github.com/user-attachments/files/19198581/custom-font-2.zip)
