### ISSUE TITLE
How to get safe area insets and viewSafeAreaInsetsDidChange on iOS?

### ISSUE THREAD

**Issue by Pranoy1c** [lynx-family/lynx#299]
On iOS, we have `viewSafeAreaInsetsDidChange` and `safeAreaInsets` to get the area which is safe to draw on. This helps prevent scenarios such as any buttons laid behind the notch can't be clicked.

1. How can my app get access to this?

2. Is there any equivalent of viewSafeAreaInsetsDidChange which notifies when these safe area insets change?

**Comment by renantatsuo** [comment]
@Pranoy1c you can do it by injecting the `safeAreaInsets` into the `lynx.__globalProps` using the `LynxView.updateGlobalProps`.

Something like:
```swift
viewSafeAreaInsetsDidChange() {
    {...}
    let globalProps: [String: Any] = [
        "safeAreaInsets": [
            "top": safeAreaInsets?.top
        ]
    ]
    lynxView.updateGlobalProps(with: globalProps)
}
```
then you can access it through `lynx.__globalProps.safeAreaInsets`

**Comment by Pranoy1c** [comment]
@renantatsuo Sorry, where do I inject this from? Like using Native Modules?

**Comment by renantatsuo** [comment]
@Pranoy1c In your iOS app.(I assumed you have integrated it https://lynxjs.org/guide/start/integrate-with-existing-apps.html)

If not, and you are only using LynxExplorer I think you can use css `env`.
```css
.safe-area-view {
  padding: env(safe-area-inset-top) env(safe-area-inset-right)
    env(safe-area-inset-bottom) env(safe-area-inset-left);
}
```
