### ISSUE TITLE
[Bug]: CSS variable referring another variable is not evaluated correctly

### ISSUE THREAD

**Issue by orionmiz** [lynx-family/lynx#816]
```css
:root {
  --color-red: red;
  --color-critical: var(--color-red); /* this is not working */
}
```

Currently, `--color-critical` cannot resolve its value(`var(--color-red)`) as `red`.

```css
.critical {
  color: var(--color-critical);
}
```

```tsx
function CriticalText() {
  return (
    <text classname="critical">This should have red color</text>
  )
}
```

So the `text` element above is missing in rendering, as if it failed to resolve the variable value.
